Trabalho 3 POO: br.usp.bbt.Usuario Class Reference
br.usp.bbt.Usuario Class Reference
Representa um usuário da biblioteca.
Public Member Functions
boolean equals (Usuario u)
int compareTo (Usuario u)
int hashCode ()
boolean estaPenalizado (long data_atual)
Determina se o usuário está penalizado no momento.
long devolveLivro (Emprestimo e, long data_atual)
Realiza devolução de um emprestimo.
Emprestimo emprestaLivro (Livro l, long data_atual) throws EmprestimoException
Cria um #Emprestimo do #Livro l em nome do Usuario.
Stack< String > pegaDados ()
Gera uma pilha com os dados desse usuário.
void carregaDados (Stack< String > dados)
Carrega os dados do usuário à partir de uma pilha.
String pegaNome ()
String pegaTipo ()
String pegaUsername ()
long pegaPena ()
long pegaQtdLivros ()
Protected Member Functions
Usuario ()
Usuario (String username, String nome, long pena, long livros, String tipo)
Protected Attributes
long livros_emprestados
Package Attributes
String tipo
Private Member Functions
void penaliza (long dias, long data_atual)
Aplica uma penalização nesse usuário.
Private Attributes
String username
String nome
long penalizado_ate
Additional Inherited Members
Static Public Member Functions inherited from br.usp.bbt.Registro
static void escreveRegistros (File arquivo, Iterable<?extends Registro > regs) throws FileNotFoundException, IOException
Escreve uma sequencia de registros num arquivo.
Detailed Description
Representa um usuário da biblioteca.
Essa classe é responsável por toda a lógica específica a um usuário em particular, por exemplo, punições e limites de emprestimos são calculados aqui, já que eles variam de acordo com o tipo e situação do usuário.
Definition at line 12 of file Usuario.java.
Constructor & Destructor Documentation
br.usp.bbt.Usuario.Usuario () protected
Definition at line 20 of file Usuario.java.
br.usp.bbt.Usuario.Usuario (String username, String nome, long pena, long livros, String tipo) protected
Definition at line 28 of file Usuario.java.
References br.usp.bbt.Usuario.nome, br.usp.bbt.Usuario.tipo, and br.usp.bbt.Usuario.username.
Member Function Documentation
void br.usp.bbt.Usuario.carregaDados (Stack< String > dados)
Carrega os dados do usuário à partir de uma pilha.
See also
pegaDados(), Registro
Implements br.usp.bbt.Registro.
Definition at line 186 of file Usuario.java.
Referenced by br.usp.bbt.Biblioteca.carregaDados().
int br.usp.bbt.Usuario.compareTo (Usuario u)
Definition at line 44 of file Usuario.java.
References br.usp.bbt.Usuario.pegaUsername().
long br.usp.bbt.Usuario.devolveLivro (Emprestimo e, long data_atual)
Realiza devolução de um emprestimo.
O número de dias de atraso é retornado à carater informativo, já que o próprio usuário já aplica a pena.
Returns
Valores negativos indicam dias de adiantamento, positivos indicam dias e atraso, e 0 significa que devolveu no limite do prazo.
Definition at line 93 of file Usuario.java.
References br.usp.bbt.Emprestimo.devolve(), br.usp.bbt.Emprestimo.devolvido(), br.usp.bbt.Usuario.livros_emprestados, br.usp.bbt.Emprestimo.pegaDataDevolucao(), and br.usp.bbt.Usuario.penaliza().
Referenced by br.usp.bbt.Biblioteca.registraDevolucao().
Emprestimo br.usp.bbt.Usuario.emprestaLivro (Livro l, long data_atual) throws EmprestimoException
Cria um #Emprestimo do #Livro l em nome do Usuario.
Tenta criar um emprestimo, aplicando as devidas restrições de cada tipo de usuário.
Returns
Um novo #Emprestimo (em aberto) no nome do próprio usuário.
Definition at line 120 of file Usuario.java.
References br.usp.bbt.Usuario.equals(), br.usp.bbt.Usuario.estaPenalizado(), br.usp.bbt.Usuario.livros_emprestados, br.usp.bbt.Usuario.pegaPena(), br.usp.bbt.Usuario.pegaQtdLivros(), br.usp.bbt.Usuario.pegaTipo(), and br.usp.bbt.Usuario.pegaUsername().
Referenced by br.usp.bbt.Biblioteca.registraEmprestimo().
boolean br.usp.bbt.Usuario.equals (Usuario u)
Definition at line 38 of file Usuario.java.
References br.usp.bbt.Usuario.pegaUsername().
Referenced by br.usp.bbt.Usuario.emprestaLivro().
boolean br.usp.bbt.Usuario.estaPenalizado (long data_atual)
Determina se o usuário está penalizado no momento.
Note que a pena só começa a ser contada à partir do dia seguinte á devoulução. Ex: Se o livro é devolvido com um dia de atraso às 11h do dia 5 o usuário será penalizado até o fim do dia 6, só podendo realizar um novo empréstimo à partir das 0h do dia 7.
Definition at line 79 of file Usuario.java.
Referenced by br.usp.bbt.Usuario.emprestaLivro(), and br.usp.bbt.Usuario.penaliza().
int br.usp.bbt.Usuario.hashCode ()
Definition at line 50 of file Usuario.java.
Stack<String> br.usp.bbt.Usuario.pegaDados ()
Gera uma pilha com os dados desse usuário.
See also
carregaDados(), Registro
Implements br.usp.bbt.Registro.
Definition at line 170 of file Usuario.java.
String br.usp.bbt.Usuario.pegaNome ()
Definition at line 195 of file Usuario.java.
References br.usp.bbt.Usuario.nome.
long br.usp.bbt.Usuario.pegaPena ()
Definition at line 198 of file Usuario.java.
References br.usp.bbt.Usuario.penalizado_ate.
Referenced by br.usp.bbt.Biblioteca.cadastraUsuario(), and br.usp.bbt.Usuario.emprestaLivro().
long br.usp.bbt.Usuario.pegaQtdLivros ()
Definition at line 199 of file Usuario.java.
References br.usp.bbt.Usuario.livros_emprestados.
Referenced by br.usp.bbt.Biblioteca.cadastraUsuario(), and br.usp.bbt.Usuario.emprestaLivro().
String br.usp.bbt.Usuario.pegaTipo ()
Definition at line 196 of file Usuario.java.
References br.usp.bbt.Usuario.tipo.
Referenced by br.usp.bbt.Usuario.emprestaLivro().
String br.usp.bbt.Usuario.pegaUsername ()
Definition at line 197 of file Usuario.java.
References br.usp.bbt.Usuario.username.
Referenced by br.usp.bbt.Biblioteca.carregaDados(), br.usp.bbt.Usuario.compareTo(), br.usp.bbt.Usuario.emprestaLivro(), and br.usp.bbt.Usuario.equals().
void br.usp.bbt.Usuario.penaliza (long dias, long data_atual) private
Aplica uma penalização nesse usuário.
Note que para a penalização ser consistente entre mudanças de datas é necessário saber a data atual para calcular a penalidade correta.
Definition at line 61 of file Usuario.java.
References br.usp.bbt.Usuario.estaPenalizado().
Referenced by br.usp.bbt.Usuario.devolveLivro().
Member Data Documentation
long br.usp.bbt.Usuario.livros_emprestados protected
Definition at line 17 of file Usuario.java.
Referenced by br.usp.bbt.Usuario.devolveLivro(), br.usp.bbt.Usuario.emprestaLivro(), and br.usp.bbt.Usuario.pegaQtdLivros().
String br.usp.bbt.Usuario.nome private
Definition at line 15 of file Usuario.java.
Referenced by br.usp.bbt.Usuario.pegaNome(), and br.usp.bbt.Usuario.Usuario().
long br.usp.bbt.Usuario.penalizado_ate private
Definition at line 16 of file Usuario.java.
Referenced by br.usp.bbt.Usuario.pegaPena().
String br.usp.bbt.Usuario.tipo package
Definition at line 18 of file Usuario.java.
Referenced by br.usp.bbt.Usuario.pegaTipo(), and br.usp.bbt.Usuario.Usuario().
String br.usp.bbt.Usuario.username private
Definition at line 14 of file Usuario.java.
Referenced by br.usp.bbt.Usuario.pegaUsername(), and br.usp.bbt.Usuario.Usuario().
The documentation for this class was generated from the following file:
src/br/usp/bbt/Usuario.java