Trabalho 3 POO: br.usp.bbt.Biblioteca Class Reference
br.usp.bbt.Biblioteca Class Reference
Public Member Functions
Biblioteca (String dir)
Cria uma biblioteca usando a data atual como referência.
Biblioteca (String dir, long data)
Cria uma biblioteca usando a data especificada.
void carregaDados () throws FileNotFoundException, IOException
Carrega os dados dos arquivos csv.
void salvaDados () throws FileNotFoundException, IOException
Salva os dados atuais nos arquivos csv.
void cadastraUsuario (String tipo, String username, String nome)
Adiciona um novo usuário na biblioteca.
void cadastraLivro (String titulo, String autor, String genero, int copias)
Adiciona uma (ou mais) cópias do livro no acrevo.
void registraEmprestimo (String username, int id) throws EmprestimoException
Tenta registrar um emprestimo em nome do usuário dado.
boolean registraDevolucao (int id)
Registra a devolução de um livro na data atual.
boolean estaDisponivel (int id)
Verifica se um livro está disponível para ser emprestado.
void defineData (long data)
Define a data usada pela biblioteca.
long pegaData ()
Retorna a data atual da biblioteca.
Static Public Member Functions
static void main (String args[]) throws Exception
Private Member Functions
Stack< String > empilhaCSVRecord (CSVRecord r)
Private Attributes
Map< String, Usuario > usuarios
Map< Integer, Livro > livros
List< Emprestimo > emprestimos
long data_atual
String dir_dados
int prox_id
Detailed Description
Definition at line 8 of file Biblioteca.java.
Constructor & Destructor Documentation
br.usp.bbt.Biblioteca.Biblioteca (String dir)
Cria uma biblioteca usando a data atual como referência.
Parameters
dir Diretório usado para carregar e salvar os dados.
Definition at line 22 of file Biblioteca.java.
Referenced by br.usp.bbt.Biblioteca.main().
br.usp.bbt.Biblioteca.Biblioteca (String dir, long data)
Cria uma biblioteca usando a data especificada.
Parameters
dir Diretório usado para carregar e salvar os dados.
data Data da biblioteca simulada.
Definition at line 33 of file Biblioteca.java.
References br.usp.bbt.Biblioteca.carregaDados().
Member Function Documentation
void br.usp.bbt.Biblioteca.cadastraLivro (String titulo, String autor, String genero, int copias)
Adiciona uma (ou mais) cópias do livro no acrevo.
Definition at line 140 of file Biblioteca.java.
References br.usp.bbt.Biblioteca.prox_id.
Referenced by br.usp.bbt.Biblioteca.main().
void br.usp.bbt.Biblioteca.cadastraUsuario (String tipo, String username, String nome)
Adiciona um novo usuário na biblioteca.
Se um usuário com o mesmo username já estiver cadastrado nada acontece.
Definition at line 125 of file Biblioteca.java.
References br.usp.bbt.Usuario.pegaPena(), and br.usp.bbt.Usuario.pegaQtdLivros().
Referenced by br.usp.bbt.Biblioteca.main().
void br.usp.bbt.Biblioteca.carregaDados () throws FileNotFoundException, IOException
Carrega os dados dos arquivos csv.
AVISO: Essa função sobrescreve quaisquer dados atualmente carregados na memória.
Definition at line 54 of file Biblioteca.java.
References br.usp.bbt.Livro.carregaDados(), br.usp.bbt.Emprestimo.carregaDados(), br.usp.bbt.Usuario.carregaDados(), br.usp.bbt.Biblioteca.empilhaCSVRecord(), br.usp.bbt.Livro.pegaId(), and br.usp.bbt.Usuario.pegaUsername().
Referenced by br.usp.bbt.Biblioteca.Biblioteca().
void br.usp.bbt.Biblioteca.defineData (long data)
Define a data usada pela biblioteca.
Se a data for menor que zero, o relogio do sistema é usado. Caso contrário a data é congelada no dia especificado.
Definition at line 254 of file Biblioteca.java.
Referenced by br.usp.bbt.Biblioteca.main().
Stack<String> br.usp.bbt.Biblioteca.empilhaCSVRecord (CSVRecord r) private
Definition at line 265 of file Biblioteca.java.
Referenced by br.usp.bbt.Biblioteca.carregaDados().
boolean br.usp.bbt.Biblioteca.estaDisponivel (int id)
Verifica se um livro está disponível para ser emprestado.
Aviso: Além de não estar emprestado no momento, para que um livro esteja disponível também não pode haver nenhum registro de empréstimo do mesmo livro numa data futura. Ou seja, para que o livro esteja disponível todas as datas de devolução deve ser anteriores à data atual e não pode haver um empréstimo em aberto.
Returns
true Se o livro existir e estiver disponível.
Definition at line 229 of file Biblioteca.java.
References br.usp.bbt.Biblioteca.pegaData().
Referenced by br.usp.bbt.Biblioteca.registraEmprestimo().
static void br.usp.bbt.Biblioteca.main (String args[]) throws Exception static
Definition at line 273 of file Biblioteca.java.
References br.usp.bbt.Biblioteca.Biblioteca(), br.usp.bbt.Biblioteca.cadastraLivro(), br.usp.bbt.Biblioteca.cadastraUsuario(), br.usp.bbt.Biblioteca.defineData(), br.usp.bbt.Biblioteca.pegaData(), br.usp.bbt.Biblioteca.registraDevolucao(), br.usp.bbt.Biblioteca.registraEmprestimo(), and br.usp.bbt.Biblioteca.salvaDados().
long br.usp.bbt.Biblioteca.pegaData ()
Retorna a data atual da biblioteca.
Definition at line 259 of file Biblioteca.java.
References br.usp.bbt.Biblioteca.data_atual.
Referenced by br.usp.bbt.Biblioteca.estaDisponivel(), br.usp.bbt.Biblioteca.main(), br.usp.bbt.Biblioteca.registraDevolucao(), and br.usp.bbt.Biblioteca.registraEmprestimo().
boolean br.usp.bbt.Biblioteca.registraDevolucao (int id)
Registra a devolução de um livro na data atual.
Tenta fazer a devolução de um livro. Se o livro não existir ou não estiver emprestado nada acontece.
Nota: Em caso de atraso o proprio usuário calcula e aplica a penalidade após a devolução.
Parameters
id ID do livro sendo devolvido.
Returns
true se achou e devolveu com sucesso.
Definition at line 190 of file Biblioteca.java.
References br.usp.bbt.Usuario.devolveLivro(), and br.usp.bbt.Biblioteca.pegaData().
Referenced by br.usp.bbt.Biblioteca.main().
void br.usp.bbt.Biblioteca.registraEmprestimo (String username, int id) throws EmprestimoException
Tenta registrar um emprestimo em nome do usuário dado.
O trabalho de verificar se o empréstimo é válido é dividido entre a biblioteca e o usuário: enquanto a biblioteca verifica a disponibilidade do livro, o usuário se responsabiliza por verificar limites de emprestimos, tipos de livros e penalidades.
Se por algum motivo não for possível fazer o empréstimo, uma excessão é lançada descrevendo o motivo.
Definition at line 158 of file Biblioteca.java.
References br.usp.bbt.Usuario.emprestaLivro(), br.usp.bbt.Biblioteca.estaDisponivel(), and br.usp.bbt.Biblioteca.pegaData().
Referenced by br.usp.bbt.Biblioteca.main().
void br.usp.bbt.Biblioteca.salvaDados () throws FileNotFoundException, IOException
Salva os dados atuais nos arquivos csv.
AVISO: Essa função sobrescreve os arquivos de dados.
Definition at line 109 of file Biblioteca.java.
References br.usp.bbt.Registro.escreveRegistros().
Referenced by br.usp.bbt.Biblioteca.main().
Member Data Documentation
long br.usp.bbt.Biblioteca.data_atual private
Definition at line 13 of file Biblioteca.java.
Referenced by br.usp.bbt.Biblioteca.pegaData().
String br.usp.bbt.Biblioteca.dir_dados private
Definition at line 14 of file Biblioteca.java.
List<Emprestimo> br.usp.bbt.Biblioteca.emprestimos private
Definition at line 12 of file Biblioteca.java.
Map<Integer, Livro> br.usp.bbt.Biblioteca.livros private
Definition at line 11 of file Biblioteca.java.
int br.usp.bbt.Biblioteca.prox_id private
Definition at line 15 of file Biblioteca.java.
Referenced by br.usp.bbt.Biblioteca.cadastraLivro().
Map<String, Usuario> br.usp.bbt.Biblioteca.usuarios private
Definition at line 10 of file Biblioteca.java.
The documentation for this class was generated from the following file:
src/br/usp/bbt/Biblioteca.java