Trabalho 3 POO: br.usp.bbt.Livro Class Reference
br.usp.bbt.Livro Class Reference
Public Member Functions
Livro (int id, String titulo, String autor, String genero)
boolean equals (Livro l)
int compareTo (Livro l)
Stack< String > pegaDados ()
Gera uma pilha com os dados de um registro.
void carregaDados (Stack< String > dados)
Carrega os dados de um registro.
String pegaTitulo ()
String pegaGenero ()
String pegaAutor ()
int pegaId ()
Package Functions
Livro ()
Private Attributes
String titulo
String genero
String autor
int id
Additional Inherited Members
Static Public Member Functions inherited from br.usp.bbt.Registro
static void escreveRegistros (File arquivo, Iterable<?extends Registro > regs) throws FileNotFoundException, IOException
Escreve uma sequencia de registros num arquivo.
Detailed Description
Definition at line 5 of file Livro.java.
Constructor & Destructor Documentation
br.usp.bbt.Livro.Livro () package
Definition at line 12 of file Livro.java.
br.usp.bbt.Livro.Livro (int id, String titulo, String autor, String genero)
Definition at line 20 of file Livro.java.
References br.usp.bbt.Livro.autor, br.usp.bbt.Livro.genero, br.usp.bbt.Livro.id, and br.usp.bbt.Livro.titulo.
Member Function Documentation
void br.usp.bbt.Livro.carregaDados (Stack< String > dados)
Carrega os dados de um registro.
Essa função sobrescreve os dados atuais do registro com os dados encontrados na pilha. A pilha deve ser organizada da mesma forma que a pilha gerada pela função pegaDados().
See also
pegaDados()
Implements br.usp.bbt.Registro.
Definition at line 48 of file Livro.java.
Referenced by br.usp.bbt.Biblioteca.carregaDados().
int br.usp.bbt.Livro.compareTo (Livro l)
Definition at line 33 of file Livro.java.
References br.usp.bbt.Livro.pegaId().
boolean br.usp.bbt.Livro.equals (Livro l)
Definition at line 28 of file Livro.java.
References br.usp.bbt.Livro.pegaId().
String br.usp.bbt.Livro.pegaAutor ()
Definition at line 58 of file Livro.java.
References br.usp.bbt.Livro.autor.
Stack<String> br.usp.bbt.Livro.pegaDados ()
Gera uma pilha com os dados de um registro.
Essa pilha deve conter todos os dados necessários para criar e recuperar um registro válido.
See also
carregaDados()
Implements br.usp.bbt.Registro.
Definition at line 38 of file Livro.java.
String br.usp.bbt.Livro.pegaGenero ()
Definition at line 57 of file Livro.java.
References br.usp.bbt.Livro.genero.
int br.usp.bbt.Livro.pegaId ()
Definition at line 59 of file Livro.java.
References br.usp.bbt.Livro.id.
Referenced by br.usp.bbt.Biblioteca.carregaDados(), br.usp.bbt.Livro.compareTo(), and br.usp.bbt.Livro.equals().
String br.usp.bbt.Livro.pegaTitulo ()
Definition at line 56 of file Livro.java.
References br.usp.bbt.Livro.titulo.
Member Data Documentation
String br.usp.bbt.Livro.autor private
Definition at line 9 of file Livro.java.
Referenced by br.usp.bbt.Livro.Livro(), and br.usp.bbt.Livro.pegaAutor().
String br.usp.bbt.Livro.genero private
Definition at line 8 of file Livro.java.
Referenced by br.usp.bbt.Livro.Livro(), and br.usp.bbt.Livro.pegaGenero().
int br.usp.bbt.Livro.id private
Definition at line 10 of file Livro.java.
Referenced by br.usp.bbt.Livro.Livro(), and br.usp.bbt.Livro.pegaId().
String br.usp.bbt.Livro.titulo private
Definition at line 7 of file Livro.java.
Referenced by br.usp.bbt.Livro.Livro(), and br.usp.bbt.Livro.pegaTitulo().
The documentation for this class was generated from the following file:
src/br/usp/bbt/Livro.java